import localFont from "next/font/local";

import type { Metadata } from "next";
import Head from "next/head";
import { ReactNode } from "react";
import "./globals.css";

const inter_24pt = localFont({
  src: [
    { path: "./fonts/Inter_24pt-Regular.woff2", weight: "400" },
    { path: "./fonts/Inter_24pt-Medium.woff2", weight: "500" },
    { path: "./fonts/Inter_24pt-SemiBold.woff2", weight: "600" },
    { path: "./fonts/Inter_24pt-Bold.woff2", weight: "700" },
    { path: "./fonts/Inter_24pt-Black.woff2", weight: "900" },
  ],
  variable: "--font-inter_24pt",
});

export const metadata: Metadata = {
  title: "Що є, чи нема",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="uk" className="scroll-smooth">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <body className={`${inter_24pt.variable} antialiased`}>{children}</body>
    </html>
  );
};

export default RootLayout;
